CREATE SEQUENCE PROCESSING_JOB_SEQ START WITH 1 INCREMENT BY 1;

ALTER TABLE ATTACHMENT ADD (
    ORIGINAL_SIZE NUMBER(19),
    CONTENT_BLOB BLOB,
    REJECTION_REASON VARCHAR2(1000),
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE PROCESSING_JOB (
    ID NUMBER(19) PRIMARY KEY,
    MESSAGE_ID NUMBER(19) NOT NULL REFERENCES INBOX_MESSAGE(ID),
    STATUS VARCHAR2(32) NOT NULL CHECK (STATUS IN ('QUEUED','PROCESSING','SUCCEEDED','FAILED')),
    ATTEMPT_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    MAX_ATTEMPTS NUMBER(10) DEFAULT 3 NOT NULL,
    NEXT_ATTEMPT_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    LOCKED_AT TIMESTAMP WITH TIME ZONE,
    LAST_ERROR VARCHAR2(2000),
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX IDX_JOB_STATUS_NEXT ON PROCESSING_JOB(STATUS, NEXT_ATTEMPT_AT);
CREATE INDEX IDX_JOB_MESSAGE ON PROCESSING_JOB(MESSAGE_ID);
