ALTER TABLE ATTACHMENT ADD (
    MALWARE_SCAN_STATUS VARCHAR2(32) DEFAULT 'PENDING' NOT NULL,
    MALWARE_SIGNATURE VARCHAR2(500),
    SCANNED_AT TIMESTAMP WITH TIME ZONE,
    STORAGE_PROVIDER VARCHAR2(32),
    STORAGE_KEY VARCHAR2(1000),
    RETENTION_UNTIL TIMESTAMP WITH TIME ZONE,
    PURGED_AT TIMESTAMP WITH TIME ZONE
);

UPDATE ATTACHMENT
SET MALWARE_SCAN_STATUS = 'NOT_REQUIRED'
WHERE PROCESSING_STATUS IN ('REJECTED_TOO_LARGE', 'REJECTED_INVALID_PDF', 'LOGGED_UNSUPPORTED');

CREATE INDEX IDX_ATTACHMENT_SCAN_STATUS ON ATTACHMENT(MALWARE_SCAN_STATUS, PROCESSING_STATUS);
CREATE INDEX IDX_ATTACHMENT_RETENTION ON ATTACHMENT(RETENTION_UNTIL, PURGED_AT);
