-- Clinevo Inbox AI - Oracle schema
-- Synthetic test data only.

CREATE SEQUENCE INBOX_MESSAGE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ATTACHMENT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE CLASSIFICATION_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE EXTRACTED_FACT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE REVIEW_ACTION_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE AUDIT_EVENT_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE INBOX_MESSAGE (
    ID NUMBER(19) PRIMARY KEY,
    INTERNET_MESSAGE_ID VARCHAR2(512) UNIQUE,
    SENDER_ADDRESS VARCHAR2(512) NOT NULL,
    SUBJECT_LINE VARCHAR2(1000),
    RECEIVED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    BODY_TEXT CLOB,
    STATUS VARCHAR2(32) NOT NULL,
    AI_SUMMARY CLOB,
    PROCESSING_MS NUMBER(19),
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE ATTACHMENT (
    ID NUMBER(19) PRIMARY KEY,
    MESSAGE_ID NUMBER(19) NOT NULL REFERENCES INBOX_MESSAGE(ID),
    FILE_NAME VARCHAR2(1000) NOT NULL,
    MIME_TYPE VARCHAR2(255),
    SHA256 VARCHAR2(64),
    PDF_TYPE VARCHAR2(32),
    DETECTED_LANGUAGE VARCHAR2(32),
    OCR_CONFIDENCE NUMBER(5,4),
    PROCESSING_MS NUMBER(19),
    PROCESSING_STATUS VARCHAR2(32) NOT NULL
);

CREATE TABLE CLASSIFICATION (
    ID NUMBER(19) PRIMARY KEY,
    MESSAGE_ID NUMBER(19) NOT NULL REFERENCES INBOX_MESSAGE(ID),
    CATEGORY VARCHAR2(32) NOT NULL CHECK (CATEGORY IN ('ICSR','PQC','MI','NOT_RELEVANT')),
    CONFIDENCE NUMBER(5,4) NOT NULL,
    REASON VARCHAR2(2000) NOT NULL,
    MODEL_NAME VARCHAR2(255),
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE EXTRACTED_FACT (
    ID NUMBER(19) PRIMARY KEY,
    MESSAGE_ID NUMBER(19) NOT NULL REFERENCES INBOX_MESSAGE(ID),
    ATTACHMENT_ID NUMBER(19) REFERENCES ATTACHMENT(ID),
    FACT_GROUP VARCHAR2(64) NOT NULL,
    FIELD_NAME VARCHAR2(128) NOT NULL,
    FIELD_VALUE CLOB,
    CONFIDENCE NUMBER(5,4) NOT NULL,
    SOURCE_TYPE VARCHAR2(16) NOT NULL CHECK (SOURCE_TYPE IN ('EMAIL','PDF')),
    SOURCE_NAME VARCHAR2(1000) NOT NULL,
    SOURCE_PAGE NUMBER(10),
    EVIDENCE_TEXT VARCHAR2(4000),
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE REVIEW_ACTION (
    ID NUMBER(19) PRIMARY KEY,
    MESSAGE_ID NUMBER(19) NOT NULL REFERENCES INBOX_MESSAGE(ID),
    REVIEWER VARCHAR2(255) NOT NULL,
    ACTION_TYPE VARCHAR2(32) NOT NULL,
    FIELD_NAME VARCHAR2(128),
    PREVIOUS_VALUE CLOB,
    NEW_VALUE CLOB,
    NOTE VARCHAR2(2000),
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE AUDIT_EVENT (
    ID NUMBER(19) PRIMARY KEY,
    MESSAGE_ID NUMBER(19) REFERENCES INBOX_MESSAGE(ID),
    EVENT_TYPE VARCHAR2(64) NOT NULL,
    ACTOR_TYPE VARCHAR2(32) NOT NULL,
    ACTOR_ID VARCHAR2(255),
    DETAILS_JSON CLOB CHECK (DETAILS_JSON IS JSON),
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX IDX_ATTACHMENT_MESSAGE ON ATTACHMENT(MESSAGE_ID);
CREATE INDEX IDX_CLASSIFICATION_MESSAGE ON CLASSIFICATION(MESSAGE_ID);
CREATE INDEX IDX_FACT_MESSAGE ON EXTRACTED_FACT(MESSAGE_ID);
CREATE INDEX IDX_REVIEW_MESSAGE ON REVIEW_ACTION(MESSAGE_ID);
CREATE INDEX IDX_AUDIT_MESSAGE ON AUDIT_EVENT(MESSAGE_ID);
